apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: abai-k8-integration-agent-clusterrole
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: abai-k8-integration-agent-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: abai-k8-integration-agent-clusterrole
  apiGroup: "rbac.authorization.k8s.io"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abai-k8-integration-agent
spec:
  selector:
    matchLabels:
      app: abai-k8-integration-agent
  template:
    metadata:
      labels:
        app: abai-k8-integration-agent
    spec:
      containers:
        - name: abai-k8-integration-agent
          image: public.ecr.aws/fusiongate/autobotai-test-kubernetes-agent:latest
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: abai-secrets
                  key: apiKey
            - name: AGENT_ID
              valueFrom:
                secretKeyRef:
                  name: abai-secrets
                  key: agentId
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: abai-secrets
                  key: apiUrl
          ports:
            - containerPort: 9898

---
apiVersion: v1
kind: Service
metadata:
  name: abai-k8-integration-agent-service
spec:
  ports:
    - port: 90
      targetPort: 9898
      nodePort: 30002
  selector:
    app: abai-k8-integration-agent
  type: NodePort